### ISSUE TITLE
IE11 Syntax Error

### ISSUE THREAD

**Issue by justin-schroeder** [xanf/vuex-shared-mutations#8]
Fairly standard install of nuxt used in conjunction with this plugin causes a syntax error on IE11:

![screen shot 2018-05-02 at 12 16 53 am](https://user-images.githubusercontent.com/1950463/39505089-2fd5cf0a-4d9e-11e8-89d6-7c4ac935019a.png)

The SyntaxError is also occurring in vuex-shared-mutations.

**Comment by jameswragg** [comment]
We've just been diagnosing the same issue @justin-schroeder. We found two issues:
1. If the localStorage payload is too big IE doesn't fire the `storage` event
2. It seems that a `localStorage.removeItem()` creates a `storage` event with a `newValue` of "" instead of null. This seems to be a known [bug in IE](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10225054/)

So potentially [this line](https://github.com/xanf/vuex-shared-mutations/blob/6da7ccfdd0ea7329e311921b829d64cab693165e/src/index.js#L47) needs an empty string check, and we're looking at reducing our payloads flowing through the mutations.

Hope that helps.

**Comment by xanf** [comment]
Hey! Thank you very much @jameswragg  and @justin-schroeder 
I believe I will have a workaround ready in a couple of days!

**Comment by xanf** [comment]
Pushed 0.0.5 to npm - please give it a try!
